var main, err, res;
main = function (callback) {
  var result;
  (function (_$cont) {
    try {
      setTimeout(function () {
        try {
          result = 0;
          [
            10,
            20,
            30
          ].forEach(function (i) {
            result += i;
            setTimeout(function () {
              throw Error('Oops');
            }, 0);
          });
          _$cont();
        } catch (_$err) {
          _$cont(_$err);
        }
      }, 0);
    } catch (_$err) {
      _$cont(_$err);
    }
  }(function (e) {
    if (e !== undefined) {
      callback(e);
      return;
    }
    callback(null, result);
  }));
};
main(function () {
  err = arguments[0];
  res = arguments[1];
  console.log('main() finished with', err, res);
});
/* Generated by Continuation.js v0.1.2 */